version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dataprovchain-backend
    container_name: dataprovchain-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - dataprovchain-network

  db:
    image: postgres:14-alpine
    container_name: dataprovchain-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dataprovchain-network

  redis:
    image: redis:7-alpine
    container_name: dataprovchain-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - dataprovchain-network

networks:
  dataprovchain-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
